(1) 예측 데이터셋 (ETTh1)

In [6]:
import pandas as pd
pd.read_csv("../results/forecast/timexer/analysis/forecast/raw/descriptive_statistics.csv", index_col=0)

,count,mean,std,min,25%,50%,75%,max,skew
HUFL,17420.0,7.375141,7.067744,-22.705999,5.827,8.774,11.788,23.643999,-1.377876
HULL,17420.0,2.242242,2.042342,-4.756000,0.737,2.210,3.684,10.114000,0.100963
MUFL,17420.0,4.300239,6.826978,-25.087999,3.296,5.970,8.635,17.341000,-1.605226
MULL,17420.0,0.881568,1.809293,-5.934000,-0.284,0.959,2.203,7.747000,-0.138206
LUFL,17420.0,3.066062,1.164506,-1.188000,2.315,2.833,3.625,8.498000,1.266531
LULL,17420.0,0.856932,0.599552,-1.371000,0.670,0.975,1.218,3.046000,-1.362274
OT,17420.0,13.324672,8.566946,-4.080000,6.964,11.396,18.079,46.007000,0.968199

(2) 이상치 탐지 데이터셋 (PSM)
- 결측치 존재

In [7]:
pd.read_csv("../results/anomaly/timexer/analysis/anomaly/raw/descriptive_statistics.csv", index_col=0)

,count,mean,std,min,25%,50%,75%,max,skew
feature_0,132481.0,0.835810,0.067326,0.486490,0.789497,0.837290,0.880603,1.000000,0.029362
feature_1,132481.0,0.840205,0.039472,0.525682,0.820488,0.843873,0.866423,0.909956,-0.932190
feature_2,132481.0,0.634216,0.102920,0.421484,0.580170,0.603304,0.625805,1.000000,2.188373
feature_3,132481.0,0.575081,0.049675,0.380874,0.543702,0.572077,0.611127,0.676682,-0.173574
feature_4,132279.0,0.543310,0.089438,0.065106,0.471135,0.548428,0.604875,0.929442,0.037409
feature_5,132232.0,0.511753,0.077771,0.110161,0.451409,0.507439,0.559671,0.877493,0.461438
feature_6,131918.0,0.549268,0.064093,0.215909,0.505682,0.539773,0.579545,1.000000,1.143211
feature_7,132434.0,0.537706,0.090120,0.077795,0.470921,0.529834,0.588369,0.968278,0.548744
feature_8,132434.0,0.551133,0.078996,0.038693,0.490750,0.552253,0.603570,0.935128,-0.070331
feature_9,132481.0,0.545177,0.081033,0.040358,0.482553,0.545577,0.598897,0.915990,0.002611
feature_10,132434.0,0.536872,0.077413,0.039544,0.478396,0.537551,0.587654,0.916855,-0.012981
feature_11,132481.0,0.594350,0.091992,0.055413,0.528724,0.587961,0.645977,1.000000,0.429474
feature_12,132481.0,0.162954,0.011247,0.136354,0.154820,0.161464,0.169611,0.519780,1.296369
feature_13,132232.0,0.147978,0.009733,0.125056,0.140936,0.146551,0.153633,0.508938,1.751633
feature_14,132279.0,0.214346,0.013735,0.173883,0.204235,0.212650,0.222673,0.465900,0.817929
feature_15,132481.0,0.395703,0.040340,0.126150,0.366614,0.393919,0.424146,1.000000,0.000442
feature_16,132481.0,0.552609,0.078733,0.096146,0.491537,0.554260,0.605177,0.934433,0.044566
feature_17,132481.0,0.626023,0.050332,0.459456,0.585286,0.613736,0.659356,0.919789,0.933104
feature_18,132279.0,0.456716,0.100087,0.148545,0.390680,0.431563,0.478530,1.000000,1.599342
feature_19,132481.0,0.659005,0.033860,0.502730,0.638411,0.652471,0.670762,1.000000,1.902985
feature_20,132481.0,0.009992,0.010383,0.000000,0.001686,0.006745,0.015177,1.000000,12.249104
feature_21,130345.0,0.012716,0.015244,0.000000,0.000000,0.007117,0.024911,0.270463,1.427502
feature_22,132277.0,0.264333,0.095716,0.118326,0.197355,0.222880,0.327563,1.000000,1.199497
feature_23,132481.0,0.106294,0.125078,0.000000,0.017429,0.047930,0.165577,1.000000,1.622405
feature_24,132434.0,0.171198,0.070909,0.009217,0.115207,0.165899,0.221198,1.000000,0.496671

(3) 분류 데이터셋 (UEA)
- 길이 100의 시계열 훈련 40개, 테스트 40개 샘플
- 40개 샘플이 하나의 시계열이라고 봤을 때의 요약 통계량

In [11]:
pd.read_csv("../results/classification/timexer/analysis/classification/raw/shape_summary.csv", index_col=0)

             num_channels  seq_len  num_classes  total_missing
num_samples
40                      6      100            4              0

In [12]:
pd.read_csv("../results/classification/timexer/analysis/classification/raw/descriptive_statistics.csv", index_col=0)

,count,mean,std,min,25%,50%,75%,max,skew
channel,,,,,,,,,
channel_0,4000,2.552760,7.073190,-22.462128,-0.281125,0.312150,4.268634,29.363152,0.651449
channel_1,4000,-1.303937,6.794940,-27.822042,-3.589513,-0.271776,1.334675,24.805077,-0.306738
channel_2,4000,-1.026581,3.546818,-24.715273,-1.743507,-0.195069,0.279323,19.523338,-1.437703
channel_3,4000,0.019051,2.112185,-18.968540,-0.530677,0.000000,0.575289,34.866211,1.008992
channel_4,4000,-0.023958,1.820976,-18.467825,-0.412823,-0.010653,0.279654,18.212141,-0.736466
channel_5,4000,-0.055790,3.517021,-24.516344,-0.991441,0.054599,1.209837,13.948082,-1.188646