예측 데이터셋 (ETTh1)
- 정상 시계열 (ADF statistics가 critical value보다 낮음)

In [2]:
import pandas as pd
pd.read_csv("../results/forecast/timexer/analysis/forecast/raw/adf_results.csv", index_col=0)

,adf_stat,p_value,n_obs,critical_value_1%,critical_value_5%,critical_value_10%
feature,,,,,,
HUFL,-8.550517,9.250276e-14,17375,-3.430726,-2.861706,-2.566859
HULL,-5.169055,1.016534e-05,17375,-3.430726,-2.861706,-2.566859
MUFL,-8.621209,6.098079e-14,17375,-3.430726,-2.861706,-2.566859
MULL,-4.964071,2.612875e-05,17375,-3.430726,-2.861706,-2.566859
LUFL,-5.796895,4.728964e-07,17375,-3.430726,-2.861706,-2.566859
LULL,-4.772686,6.132123e-05,17375,-3.430726,-2.861706,-2.566859
OT,-3.487964,8.301649e-03,17375,-3.430726,-2.861706,-2.566859

이상치 탐지 데이터셋 (PSM)
- 비정상성이 강한 feature 존재하지만 대체로 정상 시계열

In [5]:
pd.read_csv("../results/anomaly/timexer/analysis/anomaly/raw/adf_results.csv", index_col=0)

,adf_stat,p_value,n_obs,critical_value_1%,critical_value_5%,critical_value_10%
feature,,,,,,
feature_0,-6.825983,1.947410e-09,132420,-3.430399,-2.861562,-2.566782
feature_1,-5.430173,2.926431e-06,132407,-3.430399,-2.861562,-2.566782
feature_2,-3.356274,1.254292e-02,132414,-3.430399,-2.861562,-2.566782
feature_3,-4.097330,9.784127e-04,132407,-3.430399,-2.861562,-2.566782
feature_4,-11.526348,3.927668e-21,132207,-3.430399,-2.861562,-2.566782
feature_5,-11.112570,3.629200e-20,132158,-3.430399,-2.861562,-2.566782
feature_6,-9.642378,1.508847e-16,131852,-3.430400,-2.861562,-2.566782
feature_7,-10.270877,4.004747e-18,132360,-3.430399,-2.861562,-2.566782
feature_8,-13.072778,1.941574e-24,132361,-3.430399,-2.861562,-2.566782
feature_9,-12.580910,1.911388e-23,132407,-3.430399,-2.861562,-2.566782

분류 데이터셋 (UEA)
- 40개 샘플이 모두 하나의 시계열이라고 봤을 때 정상 시계열

In [9]:
pd.read_csv("../results/classification/timexer/analysis/classification/raw/adf_results.csv", index_col=0).drop(columns=["used_lag", "icbest", "stationary_at_1%", "stationary_at_5%", "stationary_at_10%"])

,adf_stat,p_value,n_obs,critical_value_1%,critical_value_5%,critical_value_10%
channel,,,,,,
channel_0,-4.511343,1.875653e-04,3968,-3.431999,-2.862269,-2.567158
channel_1,-4.455098,2.368286e-04,3968,-3.431999,-2.862269,-2.567158
channel_2,-7.026524,6.343624e-10,3971,-3.431998,-2.862268,-2.567158
channel_3,-11.342736,1.044891e-20,3970,-3.431998,-2.862268,-2.567158
channel_4,-14.318839,1.150492e-26,3969,-3.431999,-2.862268,-2.567158
channel_5,-14.564782,4.731241e-27,3978,-3.431995,-2.862267,-2.567157